# Generated by Django 4.0.1 on 2022-01-09 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_defualtdepartment_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefualtProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('departmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='v1.defualtdepartment')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('archive', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('departmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='v1.department')),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('archive', models.IntegerField(default=0)),
                ('position', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('stepid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='v1.process')),
            ],
        ),
        migrations.CreateModel(
            name='DefualtSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('position', models.IntegerField()),
                ('stepid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to='v1.defualtprocess')),
            ],
        ),
    ]
