# Generated by Django 4.0.1 on 2022-01-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_defualtprocess_process_steps_defualtsteps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
