# Generated by Django 4.0.1 on 2022-01-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
