# Generated by Django 4.0.1 on 2022-01-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_user_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
