# Generated by Django 4.0.1 on 2022-01-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0007_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='steps',
            name='timecompleted',
            field=models.IntegerField(default=0),
        ),
    ]
