# Generated by Django 4.0.1 on 2022-01-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0009_alter_department_name_alter_process_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
